# Use root/example as user/password credentials
version: '3.1'

services:
  couple-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: couple
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1
    ports:
      - "3306:3306"
    networks:
      - couple-network
    volumes:
      - ./data/:/var/lib/mysql
      - ./etc/my.cnf:/etc/my.cnf

networks:
  couple-network:
    driver: bridge